# Generated by Django 4.2.1 on 2023-05-13 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=250)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "deadline_datetime",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Enter date and time in '2023-05-13 06:31' format",
                        null=True,
                    ),
                ),
                (
                    "task_status",
                    models.BooleanField(
                        choices=[(False, "Not done"), (True, "Done")], default=False
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        related_name="tasks", to="todo_list_app.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["task_status", "-created_datetime"],
            },
        ),
    ]
