# Generated by Django 4.2.1 on 2023-05-13 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="created_datetime",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="deadline_datetime",
            new_name="deadline",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="task_status",
            new_name="is_completed",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="tag",
            new_name="tags",
        ),
    ]
